name: chuck_norris_jokes_app
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/chuck_norris.jpg
